version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13.8
    user: postgres
    ports:
      - "54320:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata